# Generated by Django 4.1a1 on 2022-05-18 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="html_content",
            new_name="content",
        ),
        migrations.AddField(
            model_name="blog",
            name="original_link",
            field=models.CharField(default=django.utils.timezone.now, max_length=192),
            preserve_default=False,
        ),
    ]
