# Generated by Django 4.1a1 on 2022-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_options_alter_parsedsite_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
