# Generated by Django 4.1a1 on 2022-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_options_article_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="parsedsite",
            name="logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="site_logo"),
        ),
    ]
