# Generated by Django 4.1a1 on 2022-05-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_parsedsite_langauge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parsedsite",
            old_name="langauge",
            new_name="language",
        ),
    ]
