# Generated by Django 4.0.4 on 2022-05-13 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(help_text='First name', max_length=50)),
                ('middle_name', models.CharField(help_text='Middle name', max_length=50)),
                ('surname', models.CharField(help_text='Surname', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
                ('is_active', models.BooleanField(default=False, verbose_name='Account Activation status')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='Account frozen status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
