# Generated by Django 4.1a1 on 2022-05-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_groups_user_is_superuser_user_last_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="jj", help_text="Name", max_length=50),
            preserve_default=False,
        ),
    ]
